### ISSUE TITLE
Investigate `_package.json` fail.

### ISSUE THREAD

**Issue by hemanth** [hemanth/generator-falcor#1]
Well, `npm test` was green, expected it to create all the files.

//cc SBoudrias are you finding something suspicious here?

``` js
Just found a `.yo-rc.json` in a parent directory.
Setting the project root at: /private/tmp
undefined:10
  "description": "Simple faclor app",
  ^

SyntaxError: Unexpected string
    at Object.parse (native)
    at EditionInterface.module.exports [as readJSON] (/Users/Hemanth/.nvm/versions/node/v4.1.1/lib/node_modules/generator-falcor/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/read-json.js:5:17)
    at Base.determineAppname (/Users/Hemanth/.nvm/versions/node/v4.1.1/lib/node_modules/generator-falcor/node_modules/yeoman-generator/lib/base.js:743:23)
    at Base (/Users/Hemanth/.nvm/versions/node/v4.1.1/lib/node_modules/generator-falcor/node_modules/yeoman-generator/lib/base.js:145:23)
    at new child (/Users/Hemanth/.nvm/versions/node/v4.1.1/lib/node_modules/generator-falcor/node_modules/yeoman-generator/node_modules/class-extend/index.js:25:41)
    at Environment.instantiate (/Users/Hemanth/.nvm/versions/node/v4.1.1/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:297:10)
    at Environment.create (/Users/Hemanth/.nvm/versions/node/v4.1.1/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:274:15)
    at Environment.run (/Users/Hemanth/.nvm/versions/node/v4.1.1/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:333:24)
    at /Users/Hemanth/.nvm/versions/node/v4.1.1/lib/node_modules/yo/lib/cli.js:97:9
    at Environment.resolver.lookup (/Users/Hemanth/.nvm/versions/node/v4.1.1/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:50:12)
```

**Comment by SBoudrias** [comment]
Well you have a json syntax error. Should print the content of the file.

**Comment by hemanth** [comment]
I thought the same looking at the error, but the [json](https://github.com/hemanth/generator-falcor/blob/master/generators/app/templates/_package.json) is perfectly valid.
